/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as FeedDefs from './defs.defs.js'

const $nsid = 'app.bsky.feed.getFeedSkeleton'

export { $nsid }

/** Get a skeleton of a feed provided by a feed generator. Auth is optional, depending on provider requirements, and provides the DID of the requester. Implemented by Feed Generator Service. */
const main = l.query(
  $nsid,
  l.params({
    feed: l.string({ format: 'at-uri' }),
    limit: l.optional(l.integer({ default: 50, maximum: 100, minimum: 1 })),
    cursor: l.optional(l.string()),
  }),
  l.jsonPayload({
    feed: l.array(
      l.ref<FeedDefs.SkeletonFeedPost>(
        (() => FeedDefs.skeletonFeedPost) as any,
      ),
    ),
    reqId: l.optional(l.string({ maxLength: 100 })),
    cursor: l.optional(l.string()),
  }),
  ['UnknownFeed'],
)
export { main }

export type Params = l.InferMethodParams<typeof main>
export type Output = l.InferMethodOutput<typeof main>
export type OutputBody = l.InferMethodOutputBody<typeof main>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
