/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as EmbedImages from './images.defs.js'
import * as EmbedVideo from './video.defs.js'
import * as EmbedExternal from './external.defs.js'
import * as EmbedRecord from './record.defs.js'

const $nsid = 'app.bsky.embed.recordWithMedia'

export { $nsid }

type Main = {
  $type?: 'app.bsky.embed.recordWithMedia'
  media:
    | l.TypedRef<EmbedImages.Main>
    | l.TypedRef<EmbedVideo.Main>
    | l.TypedRef<EmbedExternal.Main>
    | l.TypedObject
  record: EmbedRecord.Main
}

export type { Main }

const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    media: l.typedUnion(
      [
        l.typedRef<EmbedImages.Main>((() => EmbedImages.main) as any),
        l.typedRef<EmbedVideo.Main>((() => EmbedVideo.main) as any),
        l.typedRef<EmbedExternal.Main>((() => EmbedExternal.main) as any),
      ],
      false,
    ),
    record: l.ref<EmbedRecord.Main>((() => EmbedRecord.main) as any),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main)

type View = {
  $type?: 'app.bsky.embed.recordWithMedia#view'
  media:
    | l.TypedRef<EmbedImages.View>
    | l.TypedRef<EmbedVideo.View>
    | l.TypedRef<EmbedExternal.View>
    | l.TypedObject
  record: EmbedRecord.View
}

export type { View }

const view = l.typedObject<View>(
  $nsid,
  'view',
  l.object({
    media: l.typedUnion(
      [
        l.typedRef<EmbedImages.View>((() => EmbedImages.view) as any),
        l.typedRef<EmbedVideo.View>((() => EmbedVideo.view) as any),
        l.typedRef<EmbedExternal.View>((() => EmbedExternal.view) as any),
      ],
      false,
    ),
    record: l.ref<EmbedRecord.View>((() => EmbedRecord.view) as any),
  }),
)

export { view }
